### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by FirefighterBlu3** [Blue-Labs/DispatchBuddy#5]
```
DispatchBuddy.py[12957]: Exception in thread Event Manager:
DispatchBuddy.py[12957]: Traceback (most recent call last):
DispatchBuddy.py[12957]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
DispatchBuddy.py[12957]:     self.run()
DispatchBuddy.py[12957]:   File "/usr/lib/python3.6/threading.py", line 864, in run
DispatchBuddy.py[12957]:     self._target(*self._args, **self._kwargs)
DispatchBuddy.py[12957]:   File "/var/bluelabs/DispatchBuddy/api/event.py", line 178, in scan_evg_queue
DispatchBuddy.py[12957]:     for evid in self.eventgroups[evgtype].events:
DispatchBuddy.py[12957]: RuntimeError: dictionary changed size during iteration
```

**Comment by FirefighterBlu3** [comment]
fixed by making a list() copy of the keys
